### ISSUE TITLE
Switch to python 3 string formatting

### ISSUE THREAD

**Issue by dkgermyn** [miststlkr/atat#1]
https://github.com/miststlkr/atat/blob/37556ed60ac6d072d610436becc94386d4d16af7/atat.py#L115

e.g 

short_name = "{foo}-prt-{bar}".format(foo=WHID.lower(), bar=i.lower())

**Comment by dkgermyn** [comment]
Also occurs in line 127

**Comment by dkgermyn** [comment]
And line 137

**Comment by dkgermyn** [comment]
and 93

**Comment by miststlkr** [comment]
replaced (all??) instances of %s for in-string substitution
