### ISSUE TITLE
Use an "if __name__ == "__main__":" block instead of ### MAIN ###

### ISSUE THREAD

**Issue by dkgermyn** [miststlkr/atat#3]
https://github.com/miststlkr/atat/blob/37556ed60ac6d072d610436becc94386d4d16af7/atat.py#L111

Substitute " if __name__ == "__main__": " for your ### MAIN ### comment codeblock.  It'll do the same thing, but that way this .py is a library of classes and methods instead of a script

**Comment by miststlkr** [comment]
done
